import {  Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";

const geistSans = Outfit({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
 <html lang="en">
  
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        <GoogleOneTap/>
        {children}
      </body>
    </html>
    </ClerkProvider>
   
  );
}
